FROM almalinux:9
ENV COURSE="devops" \
    TRAINER="obulanaidu" \
    DURATION="120HRS" 
CMD ["sleep", "1000"]  
#the above# it is also an work
# same like java installed in linux here java can use linux env variables